Add paru support, separate out zsh aliases

diff --git a/src/pac b/src/pac
--- a/src/pac
+++ b/src/pac
@@ -1,5 +1,17 @@
 #!/bin/bash
 
+### pac - A wrapper for pacman, yay, and paru with apt-like usage and bash globbing pattern search instead of regex.
+
+
+# Detect if paru or yay is installed and set the AUR_HELPER variable accordingly
+AUR_HELPER=""
+if command -v paru > /dev/null; then
+    AUR_HELPER="paru"
+elif command -v yay > /dev/null; then
+    AUR_HELPER="yay"
+fi
+
+# To translate -y option to --noconfirm for pacman and yay
 NOCONFIRM=""
 AURNOCONFIRM=""
 
@@ -8,7 +20,11 @@ for arg in "$@"; do
     case $arg in
         -y)
             NOCONFIRM="--noconfirm"
-            AURNOCONFIRM="--noconfirm --answerdiff None --answerclean None --mflags \"--noconfirm\""
+            if [[ $AUR_HELPER == "paru" ]]; then
+                AURNOCONFIRM="--noconfirm"
+            else
+                AURNOCONFIRM="--noconfirm --answerdiff None --answerclean None --mflags \"--noconfirm\""
+            fi
             ;;
         *)
             TEMP_ARGS+=("$arg")
@@ -17,6 +33,8 @@ for arg in "$@"; do
 done
 set -- "${TEMP_ARGS[@]}"
 
+# Prompt for sudo if not already root
+SUDO=""
 prompt_for_sudo() {
     if [[ $(id -u) -ne 0 ]]; then
         if [[ -n "$AURNOCONFIRM" ]]; then
@@ -43,11 +61,10 @@ prompt_for_sudo() {
                 exit 1
                 ;;
         esac
-    else
-      SUDO=""
     fi
 }
 
+# Print help
 help() {
         cat <<EOF
 Usage: pac <command> [options]
@@ -64,8 +81,9 @@ Commands:
     search          Search the package database
     show            Show detailed package information
     find            Find a package by binary name
-    aur-search      Search in the AUR
-    aur-install     Install a package from the AUR
+    aur search      Search in the AUR
+    aur install     Install a package from the AUR
+    aur upgrade     Upgrade AUR packages
 
 Options:
     -y              Answer yes to all questions
@@ -77,6 +95,7 @@ if [[ "$1" == "--help" ]]; then
     exit 0
 fi
 
+### Primary command handler
 case "$1" in
     update)
         prompt_for_sudo
@@ -124,14 +143,34 @@ case "$1" in
         shift
         pacman -F "$@"
     ;;
-    aur-search)
-        shift
-        yay -Ssa "$@"
-    ;;
-    aur-install)
-        shift
-        yay -S "$@" $AURNOCONFIRM
-    ;;
+    aur|--aur)
+        if [[ -z "$AUR_HELPER" ]]; then
+            echo "No AUR helper found. Please install yay or paru."
+            exit 1
+        fi
+        shift # Remove 'aur' from arguments
+        case "$1" in
+            search)
+                shift
+                $AUR_HELPER -Ssa "$@"
+                ;;
+            install)
+                shift
+                $AUR_HELPER -S "$@" $AURNOCONFIRM
+                ;;
+            upgrade)
+                if [[ $AUR_HELPER == "paru" ]]; then
+                    $AUR_HELPER -Sua $AURNOCONFIRM
+                else
+                    $AUR_HELPER $AURNOCONFIRM
+                fi
+                ;;
+            *)
+                echo "Invalid aur operation: $1"
+                exit 1
+                ;;
+        esac
+        ;;
     *)
         help
         exit 1
